In [35]:
pip install pymysql sqlalchemy pandas python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (2.0.49)
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (3.0.2)
Requirement already satisfied: greenlet>=1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import os
from dotenv import load_dotenv
import pandas as pd
from sqlalchemy import create_engine

load_dotenv()

db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')
db_host = os.getenv('DB_HOST', 'localhost')
db_port = os.getenv('DB_PORT', '3306')
db_name = os.getenv('DB_NAME')
engine = create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [37]:
def query(sql):
    return pd.read_sql(sql, con=engine)

In [38]:
query("""
    SELECT * FROM clean_freelancer
    limit 10;
""")

,freelancer_id,name,email,country,primary_skill,hourly_rate_usd,years_experience,join_date,rating_avg,total_earnings_usd,profile_complete,verified
0,FL00001,michael khan,michael.khan70@gmail.com,egypt,javascript,12.00,7.00,2023-04-05,3.6,42353.0,1,1
1,FL00002,fatima mÃ¼ller,fatima.mÃ¼ller59@outlook.com,australia,ui/ux design,15.00,3.00,2021-10-08,4.1,76361.0,0,0
2,FL00003,james mÃ¼ller,james.mÃ¼ller88@outlook.com,uk,data analysis,60.00,11.00,2018-12-26,4.0,8914.0,0,1
3,FL00004,omar yamamoto,omar.yamamoto72@outlook.com,mexico,wordpress,150.00,15.00,2016-08-08,4.8,42438.0,0,1
4,FL00005,natasha patel,natasha.patel99@outlook.com,uk,wordpress,60.00,0.00,2022-08-24,4.5,133580.0,1,1
5,FL00006,juan singh,juan.singh40@gmail.com,brazil,graphic design,75.00,10.00,2016-04-03,4.4,144627.0,0,1
6,FL00007,sergiy garcia,sergiy.garcia57@outlook.com,bangladesh,devops,75.00,7.32,2019-06-23,4.0,87119.0,1,1
7,FL00008,michael silva,michael.silva56@yahoo.com,bangladesh,video editing,20.00,15.00,2019-07-26,4.1,50362.0,1,0
8,FL00009,priya johansson,priya.johansson31@gmail.com,canada,node.js,78.45,3.00,2015-03-02,3.8,146191.0,0,0
9,FL00010,chen nguyen,chen.nguyen68@gmail.com,bangladesh,python,100.00,1.00,2015-08-23,4.8,10918.0,0,0

In [39]:
query("""
    SELECT * FROM clean_projects
    limit 10;
""")

,freelancer_id,name,email,country,primary_skill,hourly_rate_usd,years_experience,join_date,rating_avg,total_earnings_usd,profile_complete,verified
0,FL00001,michael khan,michael.khan70@gmail.com,egypt,javascript,12.00,7.00,2023-04-05,3.6,42353.0,1,1
1,FL00002,fatima mÃ¼ller,fatima.mÃ¼ller59@outlook.com,australia,ui/ux design,15.00,3.00,2021-10-08,4.1,76361.0,0,0
2,FL00003,james mÃ¼ller,james.mÃ¼ller88@outlook.com,uk,data analysis,60.00,11.00,2018-12-26,4.0,8914.0,0,1
3,FL00004,omar yamamoto,omar.yamamoto72@outlook.com,mexico,wordpress,150.00,15.00,2016-08-08,4.8,42438.0,0,1
4,FL00005,natasha patel,natasha.patel99@outlook.com,uk,wordpress,60.00,0.00,2022-08-24,4.5,133580.0,1,1
5,FL00006,juan singh,juan.singh40@gmail.com,brazil,graphic design,75.00,10.00,2016-04-03,4.4,144627.0,0,1
6,FL00007,sergiy garcia,sergiy.garcia57@outlook.com,bangladesh,devops,75.00,7.32,2019-06-23,4.0,87119.0,1,1
7,FL00008,michael silva,michael.silva56@yahoo.com,bangladesh,video editing,20.00,15.00,2019-07-26,4.1,50362.0,1,0
8,FL00009,priya johansson,priya.johansson31@gmail.com,canada,node.js,78.45,3.00,2015-03-02,3.8,146191.0,0,0
9,FL00010,chen nguyen,chen.nguyen68@gmail.com,bangladesh,python,100.00,1.00,2015-08-23,4.8,10918.0,0,0

In [40]:
query("""
    SELECT * FROM clean_reviews
    limit 10;
""")

,transaction_id,project_id,freelancer_id,amount,currency,payment_date,payment_method,platform_fee_pct,status,is_disputed
0,TX0000001,PR000638,FL00229,7983.0,USD,2024-02-23,Bank Transfer,16.08,failed,1
1,TX0000002,PR000135,FL00248,1540.0,USD,2023-05-25,Payoneer,17.23,success,1
2,TX0000003,PR000370,FL00141,2473.0,,2024-03-15,Wise,20.48,success,0
3,TX0000004,PR000776,FL00153,538317.0,GBP,2024-08-14,Stripe,13.25,success,0
4,TX0000005,PR000266,FL00199,1015.0,INR,2021-05-29,Stripe,9.07,success,1
5,TX0000006,PR000768,FL00466,1868.0,USD,,PayPal,11.53,success,0
6,TX0000008,PR001153,FL00053,7634.0,INR,2022-10-22,PayPal,18.40,success,0
7,TX0000009,PR000062,,2054.0,USD,2023-06-11,Payoneer,8.55,pending,0
8,TX0000010,PR000959,FL00236,1836.0,GBP,2023-07-28,PayPal,10.64,refunded,0
9,TX0000012,PR000515,FL00386,3039.0,PKR,2024-07-18,Payoneer,9.48,refunded,1

In [41]:
query("""
    SELECT * FROM clean_transactions
    limit 10;
""")

,transaction_id,project_id,freelancer_id,amount,currency,payment_date,payment_method,platform_fee_pct,status,is_disputed
0,TX0000001,PR000638,FL00229,7983.0,USD,2024-02-23,Bank Transfer,16.08,failed,1
1,TX0000002,PR000135,FL00248,1540.0,USD,2023-05-25,Payoneer,17.23,success,1
2,TX0000003,PR000370,FL00141,2473.0,,2024-03-15,Wise,20.48,success,0
3,TX0000004,PR000776,FL00153,538317.0,GBP,2024-08-14,Stripe,13.25,success,0
4,TX0000005,PR000266,FL00199,1015.0,INR,2021-05-29,Stripe,9.07,success,1
5,TX0000006,PR000768,FL00466,1868.0,USD,,PayPal,11.53,success,0
6,TX0000008,PR001153,FL00053,7634.0,INR,2022-10-22,PayPal,18.40,success,0
7,TX0000009,PR000062,,2054.0,USD,2023-06-11,Payoneer,8.55,pending,0
8,TX0000010,PR000959,FL00236,1836.0,GBP,2023-07-28,PayPal,10.64,refunded,0
9,TX0000012,PR000515,FL00386,3039.0,PKR,2024-07-18,Payoneer,9.48,refunded,1

In [42]:
query("DESCRIBE clean_freelancer")

                 Field    Type Null Key Default Extra
0        freelancer_id    text  YES        None
1                 name    text  YES        None
2                email    text  YES        None
3              country    text  YES        None
4        primary_skill    text  YES        None
5      hourly_rate_usd  double  YES        None
6     years_experience  double  YES        None
7            join_date    text  YES        None
8           rating_avg  double  YES        None
9   total_earnings_usd  double  YES        None
10    profile_complete     int  YES        None
11            verified     int  YES        None

In [43]:
query("DESCRIBE clean_projects")

                 Field    Type Null Key Default Extra
0        freelancer_id    text  YES        None
1                 name    text  YES        None
2                email    text  YES        None
3              country    text  YES        None
4        primary_skill    text  YES        None
5      hourly_rate_usd  double  YES        None
6     years_experience  double  YES        None
7            join_date    text  YES        None
8           rating_avg  double  YES        None
9   total_earnings_usd  double  YES        None
10    profile_complete     int  YES        None
11            verified     int  YES        None

In [44]:
query("DESCRIBE clean_reviews")

              Field    Type Null Key Default Extra
0    transaction_id    text  YES        None
1        project_id    text  YES        None
2     freelancer_id    text  YES        None
3            amount  double  YES        None
4          currency    text  YES        None
5      payment_date    text  YES        None
6    payment_method    text  YES        None
7  platform_fee_pct  double  YES        None
8            status    text  YES        None
9       is_disputed     int  YES        None

In [45]:
query("DESCRIBE clean_transactions")

              Field    Type Null Key Default Extra
0    transaction_id    text  YES        None
1        project_id    text  YES        None
2     freelancer_id    text  YES        None
3            amount  double  YES        None
4          currency    text  YES        None
5      payment_date    text  YES        None
6    payment_method    text  YES        None
7  platform_fee_pct  double  YES        None
8            status    text  YES        None
9       is_disputed     int  YES        None

Revenue by country

In [46]:
query("""
    SELECT f.country,
           COUNT(DISTINCT f.freelancer_id) AS total_freelancers,
           ROUND(SUM(CAST(t.amount AS DECIMAL(10,2))), 2) AS total_revenue,
           ROUND(SUM(CAST(t.amount AS DECIMAL(10,2))) / COUNT(DISTINCT f.freelancer_id), 2) AS revenue_per_freelancer
    FROM clean_freelancer f
    JOIN clean_transactions t ON f.freelancer_id = t.freelancer_id
    WHERE LOWER(t.status) = 'success'
    GROUP BY f.country
    ORDER BY total_revenue DESC
""")

        country  total_freelancers  total_revenue  revenue_per_freelancer
0            uk                 45      3771491.0                83810.91
1      pakistan                 40      2817929.0                70448.23
2       ukraine                 39      2789360.0                71522.05
3    bangladesh                 32      2614735.0                81710.47
4           usa                 26      2062101.0                79311.58
5         india                 22      1914185.0                87008.41
6       nigeria                 32      1712689.0                53521.53
7           nan                 15      1242201.0                82813.40
8   philippines                 26      1166675.0                44872.12
9       germany                 29      1121798.0                38682.69
10    australia                 30       946718.0                31557.27
11        egypt                 19       825522.0                43448.53
12      vietnam                 22       705038.0                32047.18
13       canada                 29       494402.0                17048.34
14       mexico                 33       351180.0                10641.82
15       brazil                 24       292564.0                12190.17

In [49]:
query("DESCRIBE clean_projects")

                 Field    Type Null Key Default Extra
0        freelancer_id    text  YES        None
1                 name    text  YES        None
2                email    text  YES        None
3              country    text  YES        None
4        primary_skill    text  YES        None
5      hourly_rate_usd  double  YES        None
6     years_experience  double  YES        None
7            join_date    text  YES        None
8           rating_avg  double  YES        None
9   total_earnings_usd  double  YES        None
10    profile_complete     int  YES        None
11            verified     int  YES        None

In [50]:
query("SHOW TABLES")

  Tables_in_freelancer_analysis
0              clean_freelancer
1                clean_projects
2                 clean_reviews
3            clean_transactions

Cancellation rate

In [58]:
query("""
    SELECT f.freelancer_id, f.name, f.country, f.primary_skill,
           COUNT(p.project_id) AS total_projects,
           SUM(CASE WHEN LOWER(p.status) = 'cancelled' THEN 1 ELSE 0 END) AS cancelled_projects,
           ROUND(100.0 * SUM(CASE WHEN LOWER(p.status) = 'cancelled' THEN 1 ELSE 0 END)
                 / COUNT(p.project_id), 1) AS cancel_rate_pct
    FROM clean_freelancer f
    JOIN clean_projects p ON f.freelancer_id = p.freelancer_id
    GROUP BY f.freelancer_id, f.name, f.country, f.primary_skill
    HAVING COUNT(p.project_id) >= 3
    ORDER BY 6 DESC
""")

,freelancer_id,name,country,primary_skill,total_projects,cancelled_projects,cancel_rate_pct
0,FL00387,Sunita Khan,Nigeria,PHP,12,4.0,33.3
1,FL00483,Olga Sharma,Ukraine,Graphic Design,5,3.0,60.0
2,FL00028,Amara Mbeki,Nigeria,Flutter,5,2.0,40.0
3,FL00192,David Hassan,Canada,copywriting,4,2.0,50.0
4,FL00265,Natasha Johansson,Pakistan,Python,4,2.0,50.0
...,...,...,...,...,...,...,...
195,FL00401,SARAH MÜLLER,Germany,UI/UX Design,3,0.0,0.0
196,FL00209,Maria Silva,Nigeria,WordPress,3,0.0,0.0
197,FL00498,Bjorn Brown,USA,PHP,3,0.0,0.0
198,FL00198,Lena Patel,Egypt,Data Analysis,3,0.0,0.0
199,FL00076,Nia Ahmed,Bangladesh,Video Editing,4,0.0,0.0

Top rated freelancer per category

In [59]:
query("""
    WITH ranked AS (
        SELECT f.name, f.country, p.category,
               ROUND(AVG(r.rating), 2) AS avg_rating,
               COUNT(r.review_id) AS total_reviews,
               RANK() OVER (
                   PARTITION BY p.category
                   ORDER BY AVG(r.rating) DESC
               ) AS rnk
        FROM clean_freelancer f
        JOIN clean_projects p ON f.freelancer_id = p.freelancer_id
        JOIN clean_reviews r ON p.project_id = r.project_id
        GROUP BY f.freelancer_id, f.name, f.country, p.category
    )
    SELECT category, name, country, avg_rating, total_reviews
    FROM ranked
    WHERE rnk = 1
    ORDER BY avg_rating DESC
""")

           category             name      country  avg_rating  total_reviews
0   Web Development   Emily Yamamoto    Australia       10.00              2
1        Mobile App      Bjorn Rossi     Pakistan        9.00              1
2             AI/ML       Kofi Kumar       Mexico        7.67              3
3      Data Science       Emily Khan  Philippines        7.50              2
4            DevOps  Hassan Williams       Canada        7.50              2
5           Writing      Maria Brown  Philippines        7.50              2
6         Marketing     David Hassan     Pakistan        7.00              1
7               SEO    Fatima Müller    Australia        7.00              2
8               SEO   Sergiy Johnson           UK        7.00              1
9            Design       Ravi Mbeki       Brazil        6.50              2
10           Design     Ali Yamamoto           UK        6.50              2
11            Video       Ali Sharma      Germany        6.00              3
12              NaN      Ivan Petrov    Australia        5.33              4

Freelancers with reviews below 2 stars

In [60]:
query("""
    SELECT f.freelancer_id, f.name, f.country,
           COUNT(DISTINCT p.project_id) AS total_projects,
           SUM(CASE WHEN LOWER(p.status) = 'completed' THEN 1 ELSE 0 END) AS completed_projects,
           ROUND(AVG(r.rating), 2) AS avg_rating,
           MIN(r.rating) AS lowest_rating
    FROM clean_freelancer f
    JOIN clean_projects p ON f.freelancer_id = p.freelancer_id
    JOIN clean_reviews r ON p.project_id = r.project_id
    GROUP BY f.freelancer_id, f.name, f.country
    HAVING MIN(r.rating) < 2
    ORDER BY avg_rating ASC
""")

,freelancer_id,name,country,total_projects,completed_projects,avg_rating,lowest_rating
0,FL00033,Olga Khan,Bangladesh,1,1.0,1.00,1.0
1,FL00037,Michael Yamamoto,Nigeria,1,0.0,1.00,1.0
2,FL00082,Deepak Brown,UK,1,2.0,1.00,1.0
3,FL00169,Sofia Müller,Nigeria,1,0.0,1.00,1.0
4,FL00181,Sergiy Johansson,Vietnam,1,0.0,1.00,1.0
...,...,...,...,...,...,...,...
250,FL00422,Sarah Brown,CANADA,2,4.0,4.60,1.0
251,FL00357,Zara Rossi,Nigeria,1,0.0,5.00,1.0
252,FL00358,Fatima Nguyen,USA,2,0.0,5.00,1.0
253,FL00316,Juan Müller,Pakistan,1,0.0,5.33,1.0
254,FL00191,James Ahmed,Egypt,1,0.0,5.50,1.0

Running total of earnings per freelancer

In [61]:
query("""
    SELECT f.name, t.payment_date, t.amount,
           ROUND(SUM(t.amount) OVER (
               PARTITION BY f.freelancer_id
               ORDER BY t.payment_date
               ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
           ), 2) AS running_total
    FROM clean_freelancer f
    JOIN clean_transactions t ON f.freelancer_id = t.freelancer_id
    WHERE LOWER(t.status) = 'success'
    ORDER BY f.freelancer_id, t.payment_date
""")

               name payment_date    amount  running_total
0      Michael Khan   2020-04-09    4597.0         4597.0
1      Michael Khan   2022-05-01    7395.0        11992.0
2     Fatima Müller   2020-09-08   -5913.0        -5913.0
3     Fatima Müller   2022-10-19    1727.0        -4186.0
4      James Müller          NaN  316223.0       316223.0
...             ...          ...       ...            ...
1729    Sofia Patel   2024-12-25    5401.0        17321.0
1730    Amara Singh   2020-06-29    3281.0         3281.0
1731    Amara Singh   2022-08-17    2201.0         5482.0
1732    Amara Singh   2023-02-15    4239.0         9721.0
1733    Amara Singh   2024-10-22    1599.0        11320.0

[1734 rows x 4 columns]

Higher budget = better reviews?

In [62]:
query("""
    SELECT
        CASE
            WHEN p.budget_usd < 500  THEN '1. Low (< $500)'
            WHEN p.budget_usd < 1500 THEN '2. Mid ($500-$1500)'
            WHEN p.budget_usd < 3000 THEN '3. High ($1500-$3000)'
            ELSE '4. Premium (> $3000)'
        END AS budget_tier,
        COUNT(p.project_id) AS total_projects,
        ROUND(AVG(r.rating), 2) AS avg_rating,
        ROUND(AVG(p.budget_usd), 2) AS avg_budget
    FROM clean_projects p
    JOIN clean_reviews r ON p.project_id = r.project_id
    GROUP BY budget_tier
    ORDER BY budget_tier
""")

             budget_tier  total_projects  avg_rating  avg_budget
0        1. Low (< $500)             163        3.05      308.58
1    2. Mid ($500-$1500)             590        3.15      964.06
2  3. High ($1500-$3000)             735        3.26     2324.87
3   4. Premium (> $3000)            1287        3.20    24997.82